collections:
  posts:
    output: false

permalink: /:title/

exclude: [vendor, "Gemfile", "Gemfile.lock", "README.md", "LICENCE"]
include: ["_js", "_redirects", "_headers"]

sass:
  style: compressed